@_002_AutnenticationWithIdentity_HostAddress = http://localhost:5126


## Setup Controller

GET {{_002_AutnenticationWithIdentity_HostAddress}}/api/setup/Roles
Accept: application/json

###

POST {{_002_AutnenticationWithIdentity_HostAddress}}/api/setup/Roles/Add
Accept: */*
Content-Type: application/json

"Seller"

###


DELETE  {{_002_AutnenticationWithIdentity_HostAddress}}/api/setup/Roles/Delete
Accept: */*
Content-Type: application/json

"string"

###


GET  {{_002_AutnenticationWithIdentity_HostAddress}}/api/setup/Users
Accept: */*

###


POST   {{_002_AutnenticationWithIdentity_HostAddress}}/api/setup/Users/AddToARole?email=mt.khademi2@gmail.com&roleName=ADMINISTRATOR
Accept: */*

###

