// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MrMohande3Khademi.DAL;

#nullable disable

namespace MrMohande3Khademi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240606175132_changeRelation2")]
    partial class changeRelation2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("MrMohande3Khademi.DAL.Entities.MovieEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InsertDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDateTime = new DateTime(2024, 6, 6, 21, 21, 32, 188, DateTimeKind.Local).AddTicks(8384),
                            CreatedBy = "Mt.khademi",
                            Description = "",
                            InsertDateTime = new DateTime(2024, 6, 6, 21, 21, 32, 188, DateTimeKind.Local).AddTicks(8398),
                            IsDeleted = false,
                            Name = "Movie 001",
                            Rate = 10,
                            UpdateDateTime = new DateTime(2024, 6, 6, 21, 21, 32, 188, DateTimeKind.Local).AddTicks(8397)
                        },
                        new
                        {
                            Id = 2,
                            CreateDateTime = new DateTime(2024, 6, 6, 21, 21, 32, 188, DateTimeKind.Local).AddTicks(8400),
                            CreatedBy = "Brother warner",
                            Description = "",
                            InsertDateTime = new DateTime(2024, 6, 6, 21, 21, 32, 188, DateTimeKind.Local).AddTicks(8402),
                            IsDeleted = false,
                            Name = "Movie 002",
                            Rate = 10,
                            UpdateDateTime = new DateTime(2024, 6, 6, 21, 21, 32, 188, DateTimeKind.Local).AddTicks(8401)
                        },
                        new
                        {
                            Id = 3,
                            CreateDateTime = new DateTime(2024, 6, 6, 21, 21, 32, 188, DateTimeKind.Local).AddTicks(8403),
                            CreatedBy = "Pixar",
                            Description = "",
                            InsertDateTime = new DateTime(2024, 6, 6, 21, 21, 32, 188, DateTimeKind.Local).AddTicks(8404),
                            IsDeleted = false,
                            Name = "Movie 003",
                            Rate = 10,
                            UpdateDateTime = new DateTime(2024, 6, 6, 21, 21, 32, 188, DateTimeKind.Local).AddTicks(8404)
                        },
                        new
                        {
                            Id = 4,
                            CreateDateTime = new DateTime(2024, 6, 6, 21, 21, 32, 188, DateTimeKind.Local).AddTicks(8405),
                            CreatedBy = "Alibaba",
                            Description = "",
                            InsertDateTime = new DateTime(2024, 6, 6, 21, 21, 32, 188, DateTimeKind.Local).AddTicks(8407),
                            IsDeleted = false,
                            Name = "Movie 004",
                            Rate = 10,
                            UpdateDateTime = new DateTime(2024, 6, 6, 21, 21, 32, 188, DateTimeKind.Local).AddTicks(8406)
                        },
                        new
                        {
                            Id = 5,
                            CreateDateTime = new DateTime(2024, 6, 6, 21, 21, 32, 188, DateTimeKind.Local).AddTicks(8408),
                            CreatedBy = "Vedio Full intertanment",
                            Description = "",
                            InsertDateTime = new DateTime(2024, 6, 6, 21, 21, 32, 188, DateTimeKind.Local).AddTicks(8410),
                            IsDeleted = false,
                            Name = "Movie 005",
                            Rate = 10,
                            UpdateDateTime = new DateTime(2024, 6, 6, 21, 21, 32, 188, DateTimeKind.Local).AddTicks(8409)
                        });
                });

            modelBuilder.Entity("MrMohande3Khademi.DAL.Entities.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControllerAccess")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserEntityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserEntityId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ControllerAccess = "api/movie",
                            Name = "administrator"
                        },
                        new
                        {
                            Id = 2,
                            ControllerAccess = "",
                            Name = "user"
                        });
                });

            modelBuilder.Entity("MrMohande3Khademi.DAL.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MrMohande3Khademi.DAL.Entities.RoleEntity", b =>
                {
                    b.HasOne("MrMohande3Khademi.DAL.Entities.UserEntity", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserEntityId");
                });

            modelBuilder.Entity("MrMohande3Khademi.DAL.Entities.UserEntity", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
