// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MrMohande3Khademi.DAL;

#nullable disable

namespace MrMohande3Khademi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240606175006_changeRelation")]
    partial class changeRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("MrMohande3Khademi.DAL.Entities.MovieEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InsertDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDateTime = new DateTime(2024, 6, 6, 21, 20, 6, 401, DateTimeKind.Local).AddTicks(7972),
                            CreatedBy = "Mt.khademi",
                            Description = "",
                            InsertDateTime = new DateTime(2024, 6, 6, 21, 20, 6, 401, DateTimeKind.Local).AddTicks(7990),
                            IsDeleted = false,
                            Name = "Movie 001",
                            Rate = 10,
                            UpdateDateTime = new DateTime(2024, 6, 6, 21, 20, 6, 401, DateTimeKind.Local).AddTicks(7988)
                        },
                        new
                        {
                            Id = 2,
                            CreateDateTime = new DateTime(2024, 6, 6, 21, 20, 6, 401, DateTimeKind.Local).AddTicks(7992),
                            CreatedBy = "Brother warner",
                            Description = "",
                            InsertDateTime = new DateTime(2024, 6, 6, 21, 20, 6, 401, DateTimeKind.Local).AddTicks(7994),
                            IsDeleted = false,
                            Name = "Movie 002",
                            Rate = 10,
                            UpdateDateTime = new DateTime(2024, 6, 6, 21, 20, 6, 401, DateTimeKind.Local).AddTicks(7994)
                        },
                        new
                        {
                            Id = 3,
                            CreateDateTime = new DateTime(2024, 6, 6, 21, 20, 6, 401, DateTimeKind.Local).AddTicks(7996),
                            CreatedBy = "Pixar",
                            Description = "",
                            InsertDateTime = new DateTime(2024, 6, 6, 21, 20, 6, 401, DateTimeKind.Local).AddTicks(7998),
                            IsDeleted = false,
                            Name = "Movie 003",
                            Rate = 10,
                            UpdateDateTime = new DateTime(2024, 6, 6, 21, 20, 6, 401, DateTimeKind.Local).AddTicks(7997)
                        },
                        new
                        {
                            Id = 4,
                            CreateDateTime = new DateTime(2024, 6, 6, 21, 20, 6, 401, DateTimeKind.Local).AddTicks(8000),
                            CreatedBy = "Alibaba",
                            Description = "",
                            InsertDateTime = new DateTime(2024, 6, 6, 21, 20, 6, 401, DateTimeKind.Local).AddTicks(8002),
                            IsDeleted = false,
                            Name = "Movie 004",
                            Rate = 10,
                            UpdateDateTime = new DateTime(2024, 6, 6, 21, 20, 6, 401, DateTimeKind.Local).AddTicks(8001)
                        },
                        new
                        {
                            Id = 5,
                            CreateDateTime = new DateTime(2024, 6, 6, 21, 20, 6, 401, DateTimeKind.Local).AddTicks(8003),
                            CreatedBy = "Vedio Full intertanment",
                            Description = "",
                            InsertDateTime = new DateTime(2024, 6, 6, 21, 20, 6, 401, DateTimeKind.Local).AddTicks(8005),
                            IsDeleted = false,
                            Name = "Movie 005",
                            Rate = 10,
                            UpdateDateTime = new DateTime(2024, 6, 6, 21, 20, 6, 401, DateTimeKind.Local).AddTicks(8004)
                        });
                });

            modelBuilder.Entity("MrMohande3Khademi.DAL.Entities.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControllerAccess")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ControllerAccess = "api/movie",
                            Name = "administrator"
                        },
                        new
                        {
                            Id = 2,
                            ControllerAccess = "",
                            Name = "user"
                        });
                });

            modelBuilder.Entity("MrMohande3Khademi.DAL.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RoleEntityUserEntity", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleEntityUserEntity");
                });

            modelBuilder.Entity("RoleEntityUserEntity", b =>
                {
                    b.HasOne("MrMohande3Khademi.DAL.Entities.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MrMohande3Khademi.DAL.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
