// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MrMohande3Khademi.DAL;

#nullable disable

namespace MrMohande3Khademi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("MrMohande3Khademi.DAL.Entities.MovieEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InsertDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDateTime = new DateTime(2024, 6, 5, 14, 36, 39, 677, DateTimeKind.Local).AddTicks(5227),
                            CreatedBy = "Mt.khademi",
                            Description = "",
                            InsertDateTime = new DateTime(2024, 6, 5, 14, 36, 39, 677, DateTimeKind.Local).AddTicks(5248),
                            IsDeleted = false,
                            Name = "Movie 001",
                            Rate = 10,
                            UpdateDateTime = new DateTime(2024, 6, 5, 14, 36, 39, 677, DateTimeKind.Local).AddTicks(5247)
                        },
                        new
                        {
                            Id = 2,
                            CreateDateTime = new DateTime(2024, 6, 5, 14, 36, 39, 677, DateTimeKind.Local).AddTicks(5250),
                            CreatedBy = "Brother warner",
                            Description = "",
                            InsertDateTime = new DateTime(2024, 6, 5, 14, 36, 39, 677, DateTimeKind.Local).AddTicks(5252),
                            IsDeleted = false,
                            Name = "Movie 002",
                            Rate = 10,
                            UpdateDateTime = new DateTime(2024, 6, 5, 14, 36, 39, 677, DateTimeKind.Local).AddTicks(5251)
                        },
                        new
                        {
                            Id = 3,
                            CreateDateTime = new DateTime(2024, 6, 5, 14, 36, 39, 677, DateTimeKind.Local).AddTicks(5253),
                            CreatedBy = "Pixar",
                            Description = "",
                            InsertDateTime = new DateTime(2024, 6, 5, 14, 36, 39, 677, DateTimeKind.Local).AddTicks(5256),
                            IsDeleted = false,
                            Name = "Movie 003",
                            Rate = 10,
                            UpdateDateTime = new DateTime(2024, 6, 5, 14, 36, 39, 677, DateTimeKind.Local).AddTicks(5255)
                        },
                        new
                        {
                            Id = 4,
                            CreateDateTime = new DateTime(2024, 6, 5, 14, 36, 39, 677, DateTimeKind.Local).AddTicks(5257),
                            CreatedBy = "Alibaba",
                            Description = "",
                            InsertDateTime = new DateTime(2024, 6, 5, 14, 36, 39, 677, DateTimeKind.Local).AddTicks(5259),
                            IsDeleted = false,
                            Name = "Movie 004",
                            Rate = 10,
                            UpdateDateTime = new DateTime(2024, 6, 5, 14, 36, 39, 677, DateTimeKind.Local).AddTicks(5258)
                        },
                        new
                        {
                            Id = 5,
                            CreateDateTime = new DateTime(2024, 6, 5, 14, 36, 39, 677, DateTimeKind.Local).AddTicks(5260),
                            CreatedBy = "Vedio Full intertanment",
                            Description = "",
                            InsertDateTime = new DateTime(2024, 6, 5, 14, 36, 39, 677, DateTimeKind.Local).AddTicks(5262),
                            IsDeleted = false,
                            Name = "Movie 005",
                            Rate = 10,
                            UpdateDateTime = new DateTime(2024, 6, 5, 14, 36, 39, 677, DateTimeKind.Local).AddTicks(5262)
                        });
                });

            modelBuilder.Entity("MrMohande3Khademi.DAL.Entities.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControllerAccess")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ControllerAccess = "movieController",
                            Name = "administrator"
                        },
                        new
                        {
                            Id = 2,
                            ControllerAccess = "",
                            Name = "user"
                        });
                });

            modelBuilder.Entity("MrMohande3Khademi.DAL.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MrMohande3Khademi.DAL.Entities.UserRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleEntity");
                });

            modelBuilder.Entity("MrMohande3Khademi.DAL.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("MrMohande3Khademi.DAL.Entities.RoleEntity", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MrMohande3Khademi.DAL.Entities.UserEntity", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MrMohande3Khademi.DAL.Entities.RoleEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MrMohande3Khademi.DAL.Entities.UserEntity", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
